import type { Metadata } from "next";
import 'bootstrap/dist/css/bootstrap.min.css';
import '../../public/styles/globals.css';



export const metadata: Metadata = {
  title: "Delta Mix",
  description: "Generated by create next app",
};

function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir="rtl" lang="ar">
      <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css" />
      </head>
      <body >{children}

      </body>
    </html>
  );
}

export default RootLayout;
